"""Tools for a copula-MSM VaR replication project."""

from src.config import (
    DATA_DIR,
    FIGURES_DIR,
    PROCESSED_DATA_DIR,
    PROJECT_ROOT,
    RAW_DATA_DIR,
    REFERENCES_DIR,
    REPORTS_DIR,
    TABLES_DIR,
    ensure_project_dirs,
)
from src.data import (
    YahooIndexSpec,
    align_return_frame,
    download_yahoo_index,
    download_yahoo_index_prices,
    load_price_csv,
    log_returns,
    resolve_yahoo_index,
    save_yahoo_index_csv,
    simple_returns,
)
from src.garch import (
    GARCHFitResult,
    build_garch_pit_frame,
    build_garch_volatility_frame,
    fit_garch_11,
    fit_garch_marginals,
    format_garch_table_3,
    garch_conditional_volatility,
    garch_diagnostics,
    garch_fit_result_to_dict,
    garch_probability_integral_transform,
    garch_results_table,
    garch_standardized_residuals,
)
from src.msm import (
    MSMFitResult,
    MSMParams,
    build_msm_pit_frame,
    fit_msm,
    fit_msm_grid,
    make_msm_states,
    msm_conditional_cdf,
    msm_filter,
    msm_filter_from_result,
    msm_fit_result_to_dict,
    msm_loglikelihood,
    msm_probability_integral_transform,
    renewal_probabilities_from_gamma_k,
    transition_matrix_from_gammas,
)
from src.copulas import (
    CopulaFitResult,
    fit_all_copulas,
    fit_copula,
    fit_copula_grid,
    format_copula_table_4,
    gaussian_copula_logpdf,
    student_copula_logpdf,
    clayton_copula_logpdf,
    rotated_clayton_copula_logpdf,
    gumbel_copula_logpdf,
    rotated_gumbel_copula_logpdf,
    frank_copula_logpdf,
    plackett_copula_logpdf,
    copula_results_table,
)
from src.plotting import (
    plot_price_evolution,
    plot_returns,
    plot_returns_and_squared_returns,
    save_plotly_figure,
)
from src.risk import (
    arch_lm_test,
    format_table_1,
    gaussian_copula_correlation,
    gaussian_var,
    historical_var,
    hill_tail_index,
    hurst_exponent,
    kupiec_pof_test,
    portfolio_returns,
    pseudo_observations,
    realized_volatility,
    simulate_gaussian_copula,
    standardize_returns,
    summary_statistics,
    var_exceedances,
    violation_rate,
)

__all__ = [
    # config
    "DATA_DIR",
    "FIGURES_DIR",
    "PROCESSED_DATA_DIR",
    "PROJECT_ROOT",
    "RAW_DATA_DIR",
    "REFERENCES_DIR",
    "REPORTS_DIR",
    "TABLES_DIR",
    "ensure_project_dirs",

    # data
    "YahooIndexSpec",
    "align_return_frame",
    "download_yahoo_index",
    "download_yahoo_index_prices",
    "load_price_csv",
    "log_returns",
    "resolve_yahoo_index",
    "save_yahoo_index_csv",
    "simple_returns",

    # GARCH
    "GARCHFitResult",
    "build_garch_pit_frame",
    "build_garch_volatility_frame",
    "fit_garch_11",
    "fit_garch_marginals",
    "format_garch_table_3",
    "garch_conditional_volatility",
    "garch_diagnostics",
    "garch_fit_result_to_dict",
    "garch_probability_integral_transform",
    "garch_results_table",
    "garch_standardized_residuals",

    # MSM
    "MSMFitResult",
    "MSMParams",
    "build_msm_pit_frame",
    "fit_msm",
    "fit_msm_grid",
    "make_msm_states",
    "msm_conditional_cdf",
    "msm_filter",
    "msm_filter_from_result",
    "msm_fit_result_to_dict",
    "msm_loglikelihood",
    "msm_probability_integral_transform",
    "renewal_probabilities_from_gamma_k",
    "transition_matrix_from_gammas",

    # copulas
    "CopulaFitResult",
    "fit_all_copulas",
    "fit_copula",
    "fit_copula_grid",
    "format_copula_table_4",
    "gaussian_copula_logpdf",
    "student_copula_logpdf",
    "clayton_copula_logpdf",
    "rotated_clayton_copula_logpdf",
    "gumbel_copula_logpdf",
    "rotated_gumbel_copula_logpdf",
    "frank_copula_logpdf",
    "plackett_copula_logpdf",
    "copula_results_table",

    # plotting
    "plot_price_evolution",
    "plot_returns",
    "plot_returns_and_squared_returns",
    "save_plotly_figure",

    # risk and statistics
    "arch_lm_test",
    "format_table_1",
    "gaussian_copula_correlation",
    "gaussian_var",
    "historical_var",
    "hill_tail_index",
    "hurst_exponent",
    "kupiec_pof_test",
    "portfolio_returns",
    "pseudo_observations",
    "realized_volatility",
    "simulate_gaussian_copula",
    "standardize_returns",
    "summary_statistics",
    "var_exceedances",
    "violation_rate",
]