"""Tools for a copula-MSM VaR replication project."""

from src.config import (
    DATA_DIR,
    FIGURES_DIR,
    PROCESSED_DATA_DIR,
    PROJECT_ROOT,
    RAW_DATA_DIR,
    REFERENCES_DIR,
    REPORTS_DIR,
    TABLES_DIR,
    ensure_project_dirs,
)
from src.data import (
    YahooIndexSpec,
    align_return_frame,
    download_yahoo_index,
    download_yahoo_index_prices,
    load_price_csv,
    log_returns,
    resolve_yahoo_index,
    save_yahoo_index_csv,
    simple_returns,
)
from src.msm import (
    MSMFitResult,
    MSMParams,
    build_msm_pit_frame,
    fit_msm,
    fit_msm_grid,
    make_msm_states,
    msm_conditional_cdf,
    msm_filter,
    msm_filter_from_result,
    msm_loglikelihood,
    msm_probability_integral_transform,
    renewal_probabilities_from_gamma_k,
    transition_matrix_from_gammas,
)
from src.plotting import (
    plot_price_evolution,
    plot_returns,
    plot_returns_and_squared_returns,
    save_plotly_figure,
)
from src.risk import (
    arch_lm_test,
    format_table_1,
    gaussian_copula_correlation,
    gaussian_var,
    historical_var,
    hill_tail_index,
    hurst_exponent,
    kupiec_pof_test,
    portfolio_returns,
    pseudo_observations,
    realized_volatility,
    simulate_gaussian_copula,
    standardize_returns,
    summary_statistics,
    var_exceedances,
    violation_rate,
)

__all__ = [
    # config
    "DATA_DIR",
    "FIGURES_DIR",
    "PROCESSED_DATA_DIR",
    "PROJECT_ROOT",
    "RAW_DATA_DIR",
    "REFERENCES_DIR",
    "REPORTS_DIR",
    "TABLES_DIR",
    "ensure_project_dirs",

    # data
    "YahooIndexSpec",
    "align_return_frame",
    "download_yahoo_index",
    "download_yahoo_index_prices",
    "load_price_csv",
    "log_returns",
    "resolve_yahoo_index",
    "save_yahoo_index_csv",
    "simple_returns",

    # MSM
    "MSMFitResult",
    "MSMParams",
    "build_msm_pit_frame",
    "fit_msm",
    "fit_msm_grid",
    "make_msm_states",
    "msm_conditional_cdf",
    "msm_filter",
    "msm_filter_from_result",
    "msm_loglikelihood",
    "msm_probability_integral_transform",
    "renewal_probabilities_from_gamma_k",
    "transition_matrix_from_gammas",

    # plotting
    "plot_price_evolution",
    "plot_returns",
    "plot_returns_and_squared_returns",
    "save_plotly_figure",

    # risk and statistics
    "arch_lm_test",
    "format_table_1",
    "gaussian_copula_correlation",
    "gaussian_var",
    "historical_var",
    "hill_tail_index",
    "hurst_exponent",
    "kupiec_pof_test",
    "portfolio_returns",
    "pseudo_observations",
    "realized_volatility",
    "simulate_gaussian_copula",
    "standardize_returns",
    "summary_statistics",
    "var_exceedances",
    "violation_rate",
]